Fix ormtests project
SELab-2/OSOC-2 pull request #520
Opened 2022-04-30 15:20 UTC by nbeteram

The tests have been fixed.

2022-05-01 10:16 UTC, Mouwrice approved these changes
Jippie!

2022-05-01 13:15 UTC, Mouwrice requested changes

2022-05-01 13:15 UTC, Mouwrice commented on backend/orm_functions/project.ts
> +            console.log(fullyAssignedY);
console.log(), begone

2022-05-02 18:38 UTC, KoenDesplenter commented on backend/orm_functions/project.ts
> +            console.log(fullyAssignedY);
I removed the logs

2022-05-02 18:40 UTC, KoenDesplenter approved these changes
Well done

2022-05-02 19:12 UTC, merged