2nd password input field user settings
SELab-2/OSOC-2 pull request #521
Opened 2022-04-30 18:56 UTC by HuanYu-Tan

fixes #488.

2022-05-01 10:18 UTC, Mouwrice requested changes
Nice addition.

2022-05-01 10:18 UTC, Mouwrice commented on frontend/components/Settings/Settings.tsx
> +            setNewPasswordError("The provided passwords must be the same");
Use the same message as from the login page to keep it consistent.

2022-05-01 13:00 UTC, Mouwrice commented on frontend/components/Settings/Settings.tsx
> +            setNewPasswordError("The provided passwords must be the same");
Maybe place the error message in a field under the retypePassword field, as in the login page.

2022-05-02 18:47 UTC, KoenDesplenter approved these changes
Great

2022-05-02 18:47 UTC, jay-tux approved these changes
:rocket:

2022-05-03 06:34 UTC, merged