Websockets users
SELab-2/OSOC-2 pull request #551
Opened 2022-05-05 18:09 UTC by BramDevlaminck

- Users get automatically redirected from `/pending` when their account gets activated.
- users get automatically redirected to `/login` when their account gets disabled.
- When a new user creates a normal account (NOT GitHub) the account becomes immediately visible to admins in the manage-users screen.

To-do?
→ There is no clean way to show the account in the manage-users screen when an account is created with GitHub login.
We can choose to do not do this, OR I could send out a message to refresh every time someone logs in using GitHub.

2022-05-07 09:53 UTC, Mouwrice requested changes
Code looks clean!

However I was not redirected to login after my account was disabled.
![image](https://user-images.githubusercontent.com/56763273/167249173-4e782497-b7ab-4ea9-8ca9-c3c02b58da39.png)

2022-05-09 08:35 UTC, BramDevlaminck commented
> Code looks clean!
> 
> However I was not redirected to login after my account was disabled. ![image](https://user-images.githubusercontent.com/56763273/167249173-4e782497-b7ab-4ea9-8ca9-c3c02b58da39.png)

I've got no clue what's happening there because it works without problems for me...
(I've tested this with an account that is also just a coach, have you done any other steps to create this problem?)

2022-05-10 07:13 UTC, Mouwrice approved these changes

2022-05-10 14:59 UTC, nbeteram approved these changes
very nice!

2022-05-10 15:09 UTC, merged