Student route unit tests
SELab-2/OSOC-2 pull request #587
Opened 2022-05-11 11:39 UTC by KoenDesplenter

This pr includes all the unit tests for the student route

2022-05-16 12:43 UTC, nbeteram approved these changes

2022-05-16 19:27 UTC, Jonathan-Vanbrabant approved these changes
The tests work for Bram so approve for me!

2022-05-16 19:29 UTC, BramDevlaminck approved these changes
coverage 
![image](https://user-images.githubusercontent.com/68779933/168667779-b342ba61-a7dc-4a35-92e6-593275678f5a.png)

2022-05-16 19:29 UTC, BramDevlaminck requested changes
"some text"

2022-05-17 12:43 UTC, nbeteram approved these changes

2022-05-17 12:45 UTC, merged